#lang racket

(require test-engine/racket-tests)
(require "../../interpreter.rkt")

(check-expect (interpret "test1.txt") 20)
(check-expect (interpret "test2.txt") 164)
(check-expect (interpret "test3.txt") 32)
(check-expect (interpret "test4.txt") 2)
(check-error (interpret "test5.txt") "Variable referenced before declaration: min")
(check-expect (interpret "test6.txt") 25)
(check-expect (interpret "test7.txt") 21)
(check-expect (interpret "test8.txt") 6)
(check-expect (interpret "test9.txt") -1)
(check-expect (interpret "test10.txt") 789)
(check-error (interpret "test11.txt") "Variable referenced before declaration: y")
(check-error (interpret "test12.txt") "Variable referenced before declaration: a")
(check-error (interpret "test13.txt") "Break encountered without enclosing loop")
(check-expect (interpret "test14.txt") 12)
(check-expect (interpret "test15.txt") 125)
(check-expect (interpret "test16.txt") 110)
(check-expect (interpret "test17.txt") 2000400)
(check-expect (interpret "test18.txt") 101)
(check-error (interpret "test19.txt") "error")

(test)